/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arith.h"

int *
add_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->a + argp->b;
	return &result;
}

int *
multiply_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->a * argp->b;
	return &result;
}
