/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARITH_H_RPCGEN
#define _ARITH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intpair {
	int a;
	int b;
};
typedef struct intpair intpair;

#define ARITH_PROG 12345
#define ARITH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(intpair *, CLIENT *);
extern  int * add_1_svc(intpair *, struct svc_req *);
#define MULTIPLY 2
extern  int * multiply_1(intpair *, CLIENT *);
extern  int * multiply_1_svc(intpair *, struct svc_req *);
extern int arith_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define MULTIPLY 2
extern  int * multiply_1();
extern  int * multiply_1_svc();
extern int arith_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intpair (XDR *, intpair*);

#else /* K&R C */
extern bool_t xdr_intpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARITH_H_RPCGEN */
