/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include "arith.h"


void
arith_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	intpair  add_1_arg = {2,3};
	int  *result_2;
	intpair  multiply_1_arg = {2,3};

	clnt = clnt_create (host, ARITH_PROG, ARITH_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("add result: %d\n", *result_1);

	result_2 = multiply_1(&multiply_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("multiply result: %d\n", *result_2);

	clnt_destroy (clnt);
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	arith_prog_1 (host);
exit (0);
}
