/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "arith.h"

bool_t
xdr_intpair (XDR *xdrs, intpair *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
